// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// HealthRequest defines model for HealthRequest.
type HealthRequest struct {
	// Message Optional message for health check
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Message message
	Message string `json:"message"`
}

// HealthJSONRequestBody defines body for Health for application/json ContentType.
type HealthJSONRequestBody = HealthRequest
